services:
  anime-stock-market:
    image: adarcher/the-anime-stock-market:latest
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    volumes:
      - ./ .env.local:/app/.env.local:ro  # 